//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class blogDbEntities : DbContext
    {
        public blogDbEntities()
            : base("name=blogDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<link> link { get; set; }
        public virtual DbSet<picture> picture { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<prose> prose { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<vote> vote { get; set; }
    }
}
